name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker --version
        docker login registry.hal.davecutting.uk --username 40277434 --password Wzfqy1314
        docker build -t registry.hal.davecutting.uk/40277434/webcalc-add .
        docker push registry.hal.davecutting.uk/40277434/webcalc-add